# Generated by Django 3.0.3 on 2020-04-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.URLField(verbose_name='EMAIL')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('estado', models.BooleanField(default=True, verbose_name='activo/no activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True, verbose_name='categoria activada /categoria no activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha creacion ')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('contenido', models.TextField()),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='activo/no activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha cracion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
